### ISSUE TITLE
grapesjs-lory-slider : Error after save.

### ISSUE THREAD

**Issue by NguyenThanhUET** [GrapesJS/components-lory#1]
1 / I design a slider and save content (HTML  has designed) in this page into Database.
2 / Get content from DB and design again ( add some image, text into this slide).
3 => I saw Slider not working : click next slide not working...

**Comment by NguyenThanhUET** [comment]
- Data saved in DB like { 'gjs-css':"", "gjs-html": editor.getHtml(), "gjs-assets": "", "gjs-styles": editor.getCss(), "gjs-components": editor.getComponents(), "gjs-script":""  }
- I used this code to load slider

 var editor = grapesjs.init({

        height: '100%',
        width: '85%',
        container: '#gjs',
        fromElement: 1,
        showOffsets: 1,
        **storageManager: {
            type: 'remote',
            autoload: true,
            contentTypeJson: true,
            storeComponents: true,
            urlLoad: link get Data saved in DB,//
            params: {},   // For custom values on requests
        },**
        assetManager: { assets: assetsImage },
        plugins: ['gjs-preset-webpage', 'grapesjs-lory-slider'],
        pluginsOpts: {
            'grapesjs-lory-slider': {
                sliderBlock: {
                    category: 'Extra'
                }
            },:
............
...............
Please help me review it.

**Comment by cvetlicni** [comment]
@NguyenThanhUET care to share, how you solved it? :)
