### ISSUE TITLE
Bug: Automaticly selects .gjs-lory-slide

### ISSUE THREAD

**Issue by BerkeAras** [GrapesJS/components-lory#10]
The Slider automaticly selects .gjs-lory-slide on clicking a slide. It changes the Background Image for every slide automaticly.

**Comment by Franci5co5aoco** [comment]
@BerkeAras 

Check the example:  https://github.com/artf/grapesjs/blob/gh-pages/demo.html

As you can see you must add `selectorManager: { componentFirst: true }` to the init if you want to target the id (not the class) of the slide when you select it.

@artf maybe it could be a good idea to add this information to the `README ` ?

It was a little bit confusing for me also.
