### ISSUE TITLE
Status of this plugin

### ISSUE THREAD

**Issue by lexoyo** [GrapesJS/components-lory#13]
Hello
I see that this plugin is not in the official web page demo anymore
Also I tried to use it and had a strange "default is readonly" error
Is this plugin still maintained? Should I insist on debuging my project?
if someone sees this question, thank you for your answer :)

**Comment by artf** [comment]
I'd say as [lory](https://github.com/loryjs/lory) is not maintained anymore (last commit in  Jan 2019) probably it doesn't make sense to maintain this plugin either (at least from my opinion)

**Comment by lexoyo** [comment]
Ok thank you, I'll probably not invest too much time in it then
Maybe for silex i can create a slideshow with https://splidejs.com/
Thank you @artf !
