### ISSUE TITLE
_createAssigner.js:13 Uncaught TypeError: Cannot set property defaults of #<n> which has only a getter     at _createAssigner.js:13:51

### ISSUE THREAD

**Issue by chithraM** [GrapesJS/components-lory#15]
Latest version grapes.min.js using lory-slider plugin called i got this error? how can i solve this error?
![image](https://github.com/GrapesJS/components-lory/assets/11489469/cbfa3406-2c86-4528-8c5c-1bc4e28cc9e0)

**Comment by artf** [comment]
https://github.com/GrapesJS/components-lory/issues/13#issuecomment-1491881898
