### ISSUE TITLE
Autoplay option for slider editor control

### ISSUE THREAD

**Issue by vannem-osius-com** [GrapesJS/components-lory#2]
There is no autoplay option for slider control in component settings. Is there anyway you can incorporate?

**Comment by NguyenThanhUET** [comment]
You can do this:
function initTriggerAutorunSlider() {
        ////trigger slider image
        var btnNext = $('.gjs-lory-next');
        if (btnNext !== 'undefined') {
            setInterval(function () { $(btnNext).trigger('click'); }, 3000);
        }
    }
 $(document).ready(function () {
             initTriggerAutorunSlider();
})

**Comment by artf** [comment]
Unfortunately, there is no autoplay option inside lory https://github.com/meandmax/lory/issues/436

**Comment by karimiDev** [comment]
@artf
hi
how use auto slider in grapesjs?

**Comment by karimiDev** [comment]
@artf 
please help me

**Comment by artf** [comment]
@karimiDev https://github.com/artf/grapesjs-lory-slider/issues/2#issuecomment-375908557

**Comment by karimiDev** [comment]
@artf thank you
but  I use
grapesjs-lory-slider.min.js
but It is different with this example

**Comment by karimiDev** [comment]
@artf thank you
but I use
grapesjs-lory-slider.min.js
and It is different with this example

**Comment by karimiDev** [comment]
Hi
please help me @NguyenThanhUET 
I used your code but no changes

**Comment by NguyenThanhUET** [comment]
@karimiDev , Sorry, I haven't reviewed it in a long time
