### ISSUE TITLE
[BUG] Import/Export

### ISSUE THREAD

**Issue by blairpanek** [GrapesJS/components-lory#4]
When exporting and importing this block the Slider component isn't recognized. It saves functionality but not the component's name. Same kind of issue with the Countdown block as well, but countdown has no functionality.

**Comment by markusvisse** [comment]
I would suggest adding attribute 'data-lory-slider':true. This way it will be auto set on the element which means it will be visible in generated HTML, so then while importing and checking if the component has the attribute it will be true. This simple fix works for me.
In case you don't know what to do and how to compile it, just add this fragment: `attributes:{'data-lory-slider': true},` in grapesjs-lory-slider.min.js right after `{name:"Slider",` this should fix the problem with importing the code. I have just tested this and it works form me (as it was broken before as well).

**Comment by artf** [comment]
Well, the export is not supposed to be importable. The suggestion proposed by @markusvisse should actually work, but you don't need to touch the source, you can just [update the already defined component](https://grapesjs.com/docs/modules/Components.html#update-component-type)
