### ISSUE TITLE
Dynamically choosing number of slider frames

### ISSUE THREAD

**Issue by Amir2828** [GrapesJS/components-lory#6]
Hey,

First of all great plugin.
I am trying to improve this component so it will be possible to choose how many slides are in the slider dynamically.
I was thinking about adding a trait for deciding the number of slides.
Another option is that a modal will open on slider drop and will ask you for the number of slides wanted.
I would appreciate any guidance or ideas.  
Thanks

**Comment by artf** [comment]
It's all about extending the slider component.
For traits: 
```js
// Place this code in a plugin and load it after the lory-slider one
editor.DomComponents.addType('lory-slider', {
	model: {
		defaults: {
			numslides: 3, 
			traits: [
			 // your custom traits
			]
		}
	}
})
```
For opening a modal on slider drop follow this: https://github.com/artf/grapesjs/issues/1573#issuecomment-443263452

**Comment by censonalvin** [comment]
hello is this working or not? still trying to use the lory sliders here

**Comment by artf** [comment]
@censonalvin https://github.com/GrapesJS/components-lory/issues/13#issuecomment-1491881898
