### ISSUE TITLE
Loading as a module

### ISSUE THREAD

**Issue by rmnprt** [GrapesJS/components-lory#7]
Consider changing the first argument from 'this' to 'window' in the IIFE. Otherwise, while loading it via an import command, it throws the following error -

<img width="522" alt="image" src="https://user-images.githubusercontent.com/7310012/68845456-75b67c00-06f1-11ea-8dfa-b2e2f39b8f9f.png">

Since, 'this' is undefined in modules.

**Comment by artf** [comment]
The bundle is created by webpack as an UMD
